# Generated by Django 5.1.4 on 2026-05-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_shoppinglist_stockhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
    ]
