# Generated by Django 5.1.4 on 2026-05-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_shoppinglist_is_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
