# Generated by Django 5.1.4 on 2026-05-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_shoppinglist_is_purchased_alter_inventory_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
    ]
