# Generated by Django 5.1.4 on 2026-05-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Vegetable', 'Vegetable'), ('Spice', 'Spice'), ('Masala', 'Masala'), ('Oil', 'Oil'), ('Grain', 'Grain'), ('Milk Product', 'Milk Product'), ('Sweet', 'Sweet'), ('Beverage', 'Beverage'), ('Other', 'Other')], default='Other', max_length=100)),
                ('quantity', models.FloatField(default=0)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('ltr', 'Liter'), ('ml', 'Milliliter'), ('pcs', 'Pieces')], max_length=20)),
            ],
        ),
    ]
