# Generated by Django 5.1.4 on 2026-05-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipeusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='price_per_unit',
            field=models.FloatField(default=0),
        ),
    ]
