# Generated by Django 5.1.4 on 2026-05-18 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_ingredient_id_alter_recipe_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possible_persons', models.IntegerField(default=0)),
                ('missing_ingredients', models.TextField(blank=True, null=True)),
                ('is_possible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
    ]
