# Generated by Django 5.1.4 on 2026-05-18 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_smartmealplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SmartMealPlan',
        ),
    ]
