# Generated by Django 5.1.4 on 2026-05-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_recipe_favorites_recipe_food_type_recipe_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='tamil_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
